service: interviewjs

plugins:
  - serverless-webpack
  - serverless-sentry

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    packager: 'yarn'
    includeModules: true
  sentry:
    dsn: https://6ab80a65df4c4bf286c266faa360914d:42eced0c11b44ed195b46daa72e30861@sentry.io/1035520
    release:
      version: git

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1

functions:
  publish:
    handler: story.publish
