dist: trusty
language: node_js
node_js:
  - 8

cache:
  yarn: true
  directories:
  - node_modules
  - packages/composer/node_modules
  - packages/viewer/node_modules
  - packages/styleguide/node_modules
  - packages/site/node_modules

script:
  - '[[ $TRAVIS_BRANCH != "master" ]] && SUFFIX="~$TRAVIS_BRANCH" yarn run build'
