dist: trusty
language: node_js
node_js:
- 8
cache:
  yarn: true
  directories:
  - node_modules
  - packages/composer/node_modules
  - packages/viewer/node_modules
  - packages/styleguide/node_modules
  - packages/site/node_modules
script:
- '[[ $TRAVIS_BRANCH != "master" ]] && SUFFIX="~$TRAVIS_BRANCH" yarn run build'
# - 'SUFFIX=`echo -n "~$TRAVIS_BRANCH" | sed s/~master//` yarn run build'
# - '[[ $TRAVIS_BRANCH == "master" ]] && SUFFIX="" yarn run build'

deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAIZT2LU3JYJK66ENA
  secret_access_key:
    secure: rAtDOSOOnIucrqXHcqsDSYUApS8Zz8lGS3lWImAPKOmwf/NtmiP9LsmnQV4iEmCP6x4LkEqnKH2mLoKItJPrQE21efx9EryajF0NDCc5g3NfI2rhIyY3ujK0SRx87R1ysHjTkPX3aFk2zCo13PLgQmTNYHjtGZ106nh56iIiqOV/QQ0kCp5z27v20cJ2d4W4qAY0RrDxdnEeYXLeGwj8VMr9vGGRd8MeeJeWmQJ4ek1lOeBSJ+Z75Q3PCWko2BWzUD58/jZsiUgf8qIu349OA6UVzBJoVQ301wp+4R/Qm9rvvbf3XqO6WY3UQj91VoI6BQ0z+LOcDhoWuRkqwr7QVCgwS9CQ+H5TPJ2GVewX2NWOtg45EuyzDXY0rM0a93NdFNTM9HNDelkV0S7JBHo1FR1EASDDstP8wz54e/oX+3AE5B3t21jJqKJ5IET1u+qs7ls8vKR7tzekQfPbHNu0GJeWxGg1xOSNDGbRkEkAsHEy0OKV7QDvdM1w2RtTHQoRamsk0a2p0FmsTAhC9kyPeoLMBorVzIFpUeO6m2IT6YmwaToeKaquKelmA3Wc/yQVQdRb6ahFy8A4YRy54KnTEpGstuyo9uYjpbHNKbNpAiroP9EsImMCQj0Z3ZSbYvVwkRqQGFdklRXQIiEutV8PAlW5XglllJZhGaB136dnISs=
  bucket: interviewjs.io
  local-dir: packages/composer/build/
  upload-dir: 'my~develop'
  acl: public_read
  on:
    repo: AJInteractive/InterviewJS
    branch: develop
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAIZT2LU3JYJK66ENA
  secret_access_key:
    secure: rAtDOSOOnIucrqXHcqsDSYUApS8Zz8lGS3lWImAPKOmwf/NtmiP9LsmnQV4iEmCP6x4LkEqnKH2mLoKItJPrQE21efx9EryajF0NDCc5g3NfI2rhIyY3ujK0SRx87R1ysHjTkPX3aFk2zCo13PLgQmTNYHjtGZ106nh56iIiqOV/QQ0kCp5z27v20cJ2d4W4qAY0RrDxdnEeYXLeGwj8VMr9vGGRd8MeeJeWmQJ4ek1lOeBSJ+Z75Q3PCWko2BWzUD58/jZsiUgf8qIu349OA6UVzBJoVQ301wp+4R/Qm9rvvbf3XqO6WY3UQj91VoI6BQ0z+LOcDhoWuRkqwr7QVCgwS9CQ+H5TPJ2GVewX2NWOtg45EuyzDXY0rM0a93NdFNTM9HNDelkV0S7JBHo1FR1EASDDstP8wz54e/oX+3AE5B3t21jJqKJ5IET1u+qs7ls8vKR7tzekQfPbHNu0GJeWxGg1xOSNDGbRkEkAsHEy0OKV7QDvdM1w2RtTHQoRamsk0a2p0FmsTAhC9kyPeoLMBorVzIFpUeO6m2IT6YmwaToeKaquKelmA3Wc/yQVQdRb6ahFy8A4YRy54KnTEpGstuyo9uYjpbHNKbNpAiroP9EsImMCQj0Z3ZSbYvVwkRqQGFdklRXQIiEutV8PAlW5XglllJZhGaB136dnISs=
  bucket: interviewjs.net
  local-dir: packages/viewer/build/
  upload-dir: 'story~develop'
  acl: public_read
  on:
    repo: AJInteractive/InterviewJS
    branch: develop
