dist: trusty
language: node_js
node_js:
  - 8
  - 9

cache:
  yarn: true
  directories:
  - node_modules
  - packages/composer/node_modules
  - packages/viewer/node_modules
  - packages/styleguide/node_modules
  - packages/site/node_modules

script:
  - yarn run build
